name: Check PR Merged and Closed

on:
  pull_request:
    types:
      - closed

jobs:
  check_merged_and_closed:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR was merged
        id: check_pr
        run: echo "PR_STATE=$(jq -r '.pull_request.merged' $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Print message if PR merged
        if: steps.check_pr.outputs.PR_STATE == 'true'
        run: echo "PR was merged!"
