name: Check if PR merged and closed
on:
  push:
    branches:
      - main

jobs:
  check-pr-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR merged
        uses: actions/github-script@v3
        with:
          script: |
            import json

            # Get the PR details
            pr_details = json.loads(github.event.inputs['payload'])

            # Check if the PR is merged
            merged = pr_details['pull_request']['merged']

            # Check if the PR is closed
            closed = pr_details['pull_request']['closed']

            # If the PR is merged and closed, print "PR merged"
            if merged and closed:
                print('PR merged')
